name: Seed database
on:
  workflow_run:
    workflows: ['Deploy database migrations']
    types:
      - completed
    branches:
      - main

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.6.0
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Seed database
        run: pnpm db:seed
        env:
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_NAME: ${{ secrets.ADMIN_NAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          ADMIN_ROLE: ${{ secrets.ADMIN_ROLE }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
